default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USERNAME") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD") %>
  host: <%= ENV.fetch("MYSQL_HOST") %>
  port: <%= ENV.fetch("MYSQL_PORT") %>

development:
  <<: *default
  database: <%= ENV.fetch("MYSQL_DATABASE") %>_development

test:
  <<: *default
  database: <%= ENV.fetch("MYSQL_DATABASE") %>_test

production:
  <<: *default
  database: <%= ENV.fetch("MYSQL_DATABASE") %>_production