local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
estatutos:
  service: Disk
  root: <%= Rails.root.join("storage/estatutos") %>
dnis:
  service: Disk
  root: <%= Rails.root.join("storage/dnis") %>
signatures:
  service: Disk
  root: <%= Rails.root.join("storage/signatures") %>
authorizations:
  service: Disk
  root: <%= Rails.root.join("storage/authorizations") %>